on:
  push:
    branches:
      - master

name: shiny-deploy

jobs:
  shiny-deploy:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-18.04, r: 'release', rspm: "https://packagemanager.rstudio.com/cran/__linux__/bionic/latest"}
    env:
      SHINYAPPS_NAME:   ${{ secrets.SHINYAPPS_NAME }}
      SHINYAPPS_TOKEN:  ${{ secrets.SHINYAPPS_TOKEN }}
      SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master

      - name: Install dependencies
        run: |
          options(repos = c(CRAN = "https://packagemanager.rstudio.com/all/__linux__/bionic/latest"))
          install.packages(c("rsconnect",
                             "shiny",
                             "magrittr",
                             "tidyverse",
                             "deSolve",
                             "patchwork",
                             "plotly",
                             "shinyWidgets",
                             "shinycssloaders",
                             "jsonlite"))
        shell: Rscript {0}

      - name: Deploy
        run: |
          library(rsconnect)
          setAccountInfo(name = Sys.getenv("SHINYAPPS_NAME"),
                         token = Sys.getenv("SHINYAPPS_TOKEN"),
                         secret = Sys.getenv("SHINYAPPS_SECRET"))
          deployApp(appDir = "shiny_concept",
                    appName = "MH_Surge_Modelling")
        shell: Rscript {0}
