on:
  push:
    branches:
      - master

name: shiny-deploy

jobs:
  shiny-deploy:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-18.04, r: 'release', rspm: "https://packagemanager.rstudio.com/cran/__linux__/bionic/latest"}
    env:
      SHINYAPPS_NAME:   ${{ secrets.SHINYAPPS_NAME }}
      SHINYAPPS_TOKEN:  ${{ secrets.SHINYAPPS_TOKEN }}
      SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
      GITHUB_PAT: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master

      - name: Query dependencies
        run: |
          install.packages("remotes")
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Install dependencies
        run: |
          options(repos = c(CRAN = "https://packagemanager.rstudio.com/all/__linux__/bionic/latest"))
          install.packages(c("remotes", "rsconnect"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Deploy
        run: |
          library(rsconnect)
          setAccountInfo(name = Sys.getenv("SHINYAPPS_NAME"),
                         token = Sys.getenv("SHINYAPPS_TOKEN"),
                         secret = Sys.getenv("SHINYAPPS_SECRET"))
          deployApp(appName = Sys.getenv("SHINYAPPS_NAME"))
        shell: Rscript {0}
